# GCFoundation.Web Build and Deploy pipeline
# Created: 2025-09-03
trigger:
  branches:
    include:
      - master
      - develop
      - release/*

  paths:
    include:
      - GCFoundation.Web/
      - Pipeline/

pr:
    branches:
        include:
        - master
        - develop
        - release/*
    paths:
        include:
        - GCFoundation.Web/
        - Pipeline/

name: $(date:yyyyMMdd)$(rev:.r)
pool:
  name: TBS Self Hosted

resources:
  repositories:
   - repository: self
     type: git
     ref: refs/heads/develop

   - repository: templates
     type: git
     name: 'TBS DevOps Master/DevOps Templates'
     ref: 'refs/heads/develop'
variables:
- template: commonVariables.yaml
# these are control parameters for DevSecOps tasks - not included in commonVariables for visibility.
- name: enableTruffleHogScan
  value: false
- name: allowFlaggedSecrets
  value: true

stages:
- stage: build_gcfoundationweb_app
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Job_1
    displayName: Agent job 1
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/GCFoundation.*.csproj'
        feedsToUse: select
        vstsFeed: TBS_Custom_Feed
        noCache: true
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: PowerShell@2
      displayName: Scan Packages for Vulnerabilities - PowerShell
      continueOnError: True
      env:
       BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
      inputs:
       targetType: 'inline'
       script: |
        ($output = dotnet list $env:BUILD_SOURCESDIRECTORY/GCFoundation.Web/GCFoundation.Web.csproj package --vulnerable)

        $errors = $output | Select-String '>'

        if ($errors.Count -gt 0) {
            foreach ($err in $errors) {
                Write-Host "##vso[task.logissue type=error]Found vulnerable package $err"
            }

            exit 1
        }
        exit 0
       failOnStderr: true
    - ${{ if eq(variables.enableTruffleHogScan, true) }}:
          - task: PowerShell@2
            displayName: 'Download TruffleHog'
            inputs:
              targettype: 'inline'
              script: |
                $fileUrl = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.81.9/trufflehog_3.81.9_windows_amd64.tar.gz"
                $targetPath = "$(Pipeline.Workspace)\trufflehog.tar.gz"
                Invoke-WebRequest -Uri $fileUrl -OutFile $targetPath
                Write-Host "File downloaded to $targetPath"
                
                $tempFilePath = "$(Pipeline.Workspace)\_trufflehog.tar.gz_"
                if (Test-Path $tempFilePath) {
                  Remove-Item -Path $tempFilePath -Recurse -Force
                  Write-Host "Cleaned up old temp files"
                }

          - task: ExtractFiles@1
            displayName: 'Extract TruffleHog'
            inputs:
              archiveFilePatterns: '$(PIPELINE.WORKSPACE)\trufflehog.tar.gz' # string. Required. Archive file patterns. Default: **/*.zip.
              destinationFolder: $(PIPELINE.WORKSPACE)
              cleanDestinationFolder: false
              overwriteExistingFiles: true

          - task: PowerShell@2
            displayName: 'Run TruffleHog'
            continueOnError: ${{ variables.allowFlaggedSecrets }}
            inputs:
              targettype: 'inline'
              script: |
                &"$(Pipeline.Workspace)\trufflehog.exe" filesystem $(System.DefaultWorkingDirectory) --no-update --no-verification --fail 

    - task: DotNetCoreCLI@2
      displayName: Build web app
      inputs:
        projects: '**/GCFoundation.Web.csproj'
        arguments: '--configuration $(BuildConfiguration) '
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: DotNetCoreCLI@2
      displayName: Publish Web App
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration) --output $(Build.BinariesDirectory)/publish_output
        zipAfterPublish: false
        modifyOutputPath: false
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: ArchiveFiles@2
      displayName: Archive $(Build.BinariesDirectory)/publish_output/
      inputs:
        rootFolderOrFile: $(Build.BinariesDirectory)/publish_output
        includeRootFolder: false
        archiveFile: $(Build.ArtifactStagingDirectory)/GCFoundation.Web.zip
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

- stage: deploy_gcfoundationweb_solution_dev
  dependsOn: build_gcfoundationweb_app     # must refer to stage, not job
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  ## You would think this is only needed on the build, but all subsequent stages will need it too
  
  jobs:
  - deployment: deploy_gcfoundationweb_app_dev
    variables:
      - template: './transforms/dev/appsettings.yaml'
      - template: './transforms/dev/deployment.yaml'
    environment: ${{ variables.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@3
            displayName: Create Virtual Directory - PowerShell
            continueOnError: True
            env:
              BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
            inputs:
            targetType: 'inline'
            script: |
              Function CreateVirtualApplication {
                Param($ARG, $AWAN, $WS, $PE, $PP, $VP, $US)
                $UWS = "true"
                If($WS -eq "Production" -or $US -eq "false"){
                  $UWS = "false"
                }
                If($UWS -eq "false"){
                '1'
                  $webAppSlot  = Get-AzureRmWebApp -ResourceGroupName $ARG  -Name  $AWAN
                '1.1'
                } else {
                '2'
                  $webAppSlot  = Get-AzureRmWebAppSlot  -ResourceGroupName $ARG  -Name  $AWAN -Slot $WS
                '2.1'
                }
                '--webAppSlot.siteConfig.VirtualApplications.VirtualPath: ' + $webAppSlot.siteConfig.VirtualApplications.VirtualPath
                '--VP: ' + $VP
                # Test if the virtual directory already exists, if not create it! 
                If ($webAppSlot.siteConfig.VirtualApplications.VirtualPath -notcontains $VP) {
                  # Set all the virtual properties
                  $virtApp = New-Object Microsoft.Azure.Management.WebSites.Models.VirtualApplication
                  $virtApp.VirtualPath = $VP
                  $virtApp.PhysicalPath = $PP
                  $virtApp.PreloadEnabled  = $PE

                  # Assignment of virtual properties
                  $null = $webAppSlot.siteConfig.VirtualApplications.Add($virtApp)

                  # Create the virtual directory on the slot
                  if($UWS -eq "false"){
                  '3'
                    Set-AzureRmWebApp -WebApp $webAppSlot
                  '3.1'
                  } else {
                  '4'
                    Set-AzureRmWebAppSlot -WebApp $webAppSlot
                  '4.1'
                  }
                } else {
                  for ($i = 0; $i -lt $webAppSlot.siteConfig.VirtualApplications.Count ; $i++) {
                    $webAppSlotVirtualApp = $webAppSlot.siteConfig.VirtualApplications[$i]
                    if($webAppSlotVirtualApp.VirtualPath -eq $VP){
                      $webAppSlotVirtualApp.PhysicalPath  = $PP
                    }
                  }
                  if($UWS -eq "false"){
                  '5'
                    Set-AzureRmWebApp -WebApp $webAppSlot
                  '5.1'
                  } else {
                  '6'
                    Set-AzureRmWebAppSlot -WebApp $webAppSlot
                  '6.1'
                  }
                }
              }

              # Assign the Pipeline Library (global) and Release (local) variables
              $AzureResGroup = "$(resourceGroupName)"
              $AzureWebAppName = "$(webAppName)"
              $WebSlot = "$(slotName)"
              $PreloadEnabled = $false
              $usesSlots = "$(useSlot)"

              $virtualDirectoryFullPath = "$(virtualDirectoryName)"
              if($virtualDirectoryFullPath -eq ""){
                $virtualDirectoryFullPath = "/"
              }

              $separators = "/"
              $separators2 = ";"
              $separators3 = "&"
              $option = [System.StringSplitOptions]::RemoveEmptyEntries
              $distinctVirtualDirectories = $virtualDirectoryFullPath.Split($separators2)

              for ($dvds = 0; $dvds -lt $distinctVirtualDirectories.Count ; $dvds++) {
                $distinctVirtualDirectory = $distinctVirtualDirectories[$dvds]

                If ($distinctVirtualDirectory.StartsWith("%")){
                  $virtualDirectories = $distinctVirtualDirectory.Split($separators3,$option)
                  $PhysicalPath = "site\wwwroot\" + $virtualDirectories[0].Substring(1)
                  $VirtualPath = $virtualDirectories[1]

                  If ($VirtualPath -eq "/"){
                    $VirtualPath = ""
                  }
                  $PhysicalPath = $PhysicalPath.Replace('/', '\')
                  $VirtualPath = $VirtualPath.Replace('\', '/')
                  CreateVirtualApplication -ARG $AzureResGroup -AWAN $AzureWebAppName -WS $WebSlot -PE $PreloadEnabled -PP $PhysicalPath -VP $VirtualPath -US $usesSlots
                } else {
                  $virtualDirectories = $distinctVirtualDirectory.Split($separators,$option)
                  
                  if($virtualDirectories.Count -eq 0){
                    $PhysicalPath = "site\wwwroot"
                    $VirtualPath = ""
                    
                    #CreateVirtualApplication -ARG $AzureResGroup -AWAN $AzureWebAppName -WS $WebSlot -PE $PreloadEnabled -PP $PhysicalPath -VP $VirtualPath -US $usesSlots
                  } else {
                    for ($vds = 0; $vds -lt $virtualDirectories.Count ; $vds++) {
                      $VirtualPath = "/"
                      $PhysicalPath = ""
                      for ($vps = 0; $vps -lt $vds + 1 ; $vps++) {
                        $VirtualPath = $VirtualPath + $virtualDirectories[$vps] + "/"
                        $PhysicalPath = $PhysicalPath + $virtualDirectories[$vps] + "/"
                      }
                      
                      # Set the paths
                      $PhysicalPath = "site\wwwroot\$PhysicalPath"
                      $PhysicalPath = $PhysicalPath.Replace('/', '\')
                      $VirtualPath = $VirtualPath.Replace('\', '/')
                      
                      if ($PhysicalPath.Length -gt 1) {
                        $PPlastchar = $PhysicalPath.Substring($PhysicalPath.Length-1, 1)
                        DO {
                          $PhysicalPath = $PhysicalPath.Substring(0, $PhysicalPath.Length-1)
                          $PPlastchar = $PhysicalPath.Substring($PhysicalPath.Length-1, 1)
                        } While ($PPlastchar -eq "\")
                      }

                      if ($VirtualPath.Length -gt 1) {
                        $VPlastchar = $VirtualPath.Substring($VirtualPath.Length-1, 1)
                        DO {
                          $VirtualPath = $VirtualPath.Substring(0, $VirtualPath.Length-1)
                          $VPlastchar = $VirtualPath.Substring($VirtualPath.Length-1, 1)
                        } While ($VPlastchar -eq "/")
                      }
                      
                      CreateVirtualApplication -ARG $AzureResGroup -AWAN $AzureWebAppName -WS $WebSlot -PE $PreloadEnabled -PP $PhysicalPath -VP $VirtualPath -US $usesSlots
                    }
                  }
                }
              }
            failOnStderr: true
          - template: Deploy/DotNetCore/deploy-steps.yaml@templates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              pathToPackage: ${{ variables.pathToPackage }}
              resourceGroupName: ${{ variables.resourceGroupName }}
              virtualDirectoryName: ${{ variables.virtualDirectoryName }}
              webAppName: ${{ variables.webAppName }}