# GCFoundation.Web Build and Deploy pipeline
# Created: 2025-09-03
trigger:
  branches:
    include:
      - master
      - develop
      - release/*

  paths:
    include:
      - GCFoundation.Web/
      - Pipeline/

pr:
    branches:
        include:
        - master
        - develop
        - release/*
    paths:
        include:
        - GCFoundation.Web/
        - Pipeline/

name: $(date:yyyyMMdd)$(rev:.r)
pool:
  name: TBS Self Hosted

resources:
  repositories:
   - repository: self
     type: git
     ref: refs/heads/develop

   - repository: templates
     type: git
     name: 'TBS DevOps Master/DevOps Templates'
     ref: 'refs/heads/develop'
variables:
- template: commonVariables.yaml
# these are control parameters for DevSecOps tasks - not included in commonVariables for visibility.
- name: enableTruffleHogScan
  value: false
- name: allowFlaggedSecrets
  value: true

stages:
- stage: build_gcfoundationweb_app
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Job_1
    displayName: Agent job 1
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/GCFoundation.*.csproj'
        feedsToUse: select
        vstsFeed: TBS_Custom_Feed
        noCache: true
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: PowerShell@2
      displayName: Scan Packages for Vulnerabilities - PowerShell
      continueOnError: True
      env:
       BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
      inputs:
       targetType: 'inline'
       script: |
        ($output = dotnet list $env:BUILD_SOURCESDIRECTORY/GCFoundation.Web/GCFoundation.Web.csproj package --vulnerable)

        $errors = $output | Select-String '>'

        if ($errors.Count -gt 0) {
            foreach ($err in $errors) {
                Write-Host "##vso[task.logissue type=error]Found vulnerable package $err"
            }

            exit 1
        }
        exit 0
       failOnStderr: true
    - ${{ if eq(variables.enableTruffleHogScan, true) }}:
          - task: PowerShell@2
            displayName: 'Download TruffleHog'
            inputs:
              targettype: 'inline'
              script: |
                $fileUrl = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.81.9/trufflehog_3.81.9_windows_amd64.tar.gz"
                $targetPath = "$(Pipeline.Workspace)\trufflehog.tar.gz"
                Invoke-WebRequest -Uri $fileUrl -OutFile $targetPath
                Write-Host "File downloaded to $targetPath"
                
                $tempFilePath = "$(Pipeline.Workspace)\_trufflehog.tar.gz_"
                if (Test-Path $tempFilePath) {
                  Remove-Item -Path $tempFilePath -Recurse -Force
                  Write-Host "Cleaned up old temp files"
                }

          - task: ExtractFiles@1
            displayName: 'Extract TruffleHog'
            inputs:
              archiveFilePatterns: '$(PIPELINE.WORKSPACE)\trufflehog.tar.gz' # string. Required. Archive file patterns. Default: **/*.zip.
              destinationFolder: $(PIPELINE.WORKSPACE)
              cleanDestinationFolder: false
              overwriteExistingFiles: true

          - task: PowerShell@2
            displayName: 'Run TruffleHog'
            continueOnError: ${{ variables.allowFlaggedSecrets }}
            inputs:
              targettype: 'inline'
              script: |
                &"$(Pipeline.Workspace)\trufflehog.exe" filesystem $(System.DefaultWorkingDirectory) --no-update --no-verification --fail 

    - task: DotNetCoreCLI@2
      displayName: Build web app
      inputs:
        projects: '**/GCFoundation.Web.csproj'
        arguments: '--configuration $(BuildConfiguration) '
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: DotNetCoreCLI@2
      displayName: Publish Web App
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration) --output $(Build.BinariesDirectory)/publish_output
        zipAfterPublish: false
        modifyOutputPath: false
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: ArchiveFiles@2
      displayName: Archive $(Build.BinariesDirectory)/publish_output/
      inputs:
        rootFolderOrFile: $(Build.BinariesDirectory)/publish_output
        includeRootFolder: false
        archiveFile: $(Build.ArtifactStagingDirectory)/GCFoundation.Web.zip
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

- stage: deploy_gcfoundationweb_solution_dev
  dependsOn: build_gcfoundationweb_app     # must refer to stage, not job
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  ## You would think this is only needed on the build, but all subsequent stages will need it too
  
  jobs:
  - deployment: deploy_gcfoundationweb_app_dev
    variables:
      - template: './transforms/dev/appsettings.yaml'
      - template: './transforms/dev/deployment.yaml'
    environment: ${{ variables.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: Deploy/DotNetCore/deploy-steps.yaml@templates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              pathToPackage: ${{ variables.pathToPackage }}
              resourceGroupName: ${{ variables.resourceGroupName }}
              slotName: ${{ variables.slotName }}
              virtualDirectoryName: ${{ variables.virtualDirectoryName }}
              webAppName: ${{ variables.webAppName }}

- stage: deploy_gcfoundationweb_solution_qa
  dependsOn: deploy_gcfoundationweb_solution_dev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  
  jobs:
  - deployment: deploy_gcfoundationweb_app_qa
    variables:
      - template: './transforms/qa/appsettings.yaml'
      - template: './transforms/qa/deployment.yaml'
    environment: ${{ variables.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: Deploy/DotNetCore/deploy-steps.yaml@templates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              pathToPackage: ${{ variables.pathToPackage }}
              resourceGroupName: ${{ variables.resourceGroupName }}
              slotName: ${{ variables.slotName }}
              virtualDirectoryName: ${{ variables.virtualDirectoryName }}
              webAppName: ${{ variables.webAppName }}

- stage: deploy_gcfoundationweb_solution_uat
  dependsOn: deploy_gcfoundationweb_solution_qa
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  
  jobs:
  - deployment: deploy_gcfoundationweb_app_uat
    variables:
      - template: './transforms/uat/appsettings.yaml'
      - template: './transforms/uat/deployment.yaml'
    environment: ${{ variables.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: Deploy/DotNetCore/deploy-steps.yaml@templates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              pathToPackage: ${{ variables.pathToPackage }}
              resourceGroupName: ${{ variables.resourceGroupName }}
              slotName: ${{ variables.slotName }}
              virtualDirectoryName: ${{ variables.virtualDirectoryName }}
              webAppName: ${{ variables.webAppName }}

- stage: deploy_gcfoundationweb_solution_prod
  dependsOn: deploy_gcfoundationweb_solution_uat
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  
  jobs:
  - deployment: deploy_gcfoundationweb_app_prod
    variables:
      - template: './transforms/prod/appsettings.yaml'
      - template: './transforms/prod/deployment.yaml'
    environment: ${{ variables.deploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: Deploy/DotNetCore/deploy-steps.yaml@templates
            parameters:
              azureSubscription: ${{ variables.azureSubscription }}
              pathToPackage: ${{ variables.pathToPackage }}
              resourceGroupName: ${{ variables.resourceGroupName }}
              slotName: ${{ variables.slotName }}
              virtualDirectoryName: ${{ variables.virtualDirectoryName }}
              webAppName: ${{ variables.webAppName }}