# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- template: variables.yaml
- name: enableTruffleHogScan
  value: false
- name: allowFlaggedSecrets
  value: true
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

stages:
- stage: Build
  displayName: 'Build and Scan'
  jobs:
  - job: Job_1
    displayName: Agent job 1
    steps:
    - task: NuGetToolInstaller@1
    
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
  - job: Job_2
    displayName: Agent job 2
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: ${{ variables.dotnetSdkVersion }}
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: ${{ variables.projects }}
        feedsToUse: select
        vstsFeed: TBS_Custom_Feed
        noCache: true
        verbosityRestore: Detailed
        verbosityPack: Detailed