# QA AppSettings Variables
variables:
- name: Infrastructure.Environment
  value: 'QA'

- name: FoundationComponentsSettings.VirtualDirectoryName
  value: 'gcfoundation'

- name: ASPNETCORE_PATHBASE
  value: '/gcfoundation'