//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Installation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Installation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Installation", typeof(Installation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Enabled.
        /// </summary>
        public static string GlobalResources_AlwaysEnabled {
            get {
                return ResourceManager.GetString("GlobalResources_AlwaysEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Loading Order.
        /// </summary>
        public static string GlobalResources_CssLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CssLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following resources are currently configured to be loaded globally:.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Description {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CSS:.
        /// </summary>
        public static string GlobalResources_DefaultCss_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultCss_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Note:&lt;/strong&gt; Default foundation CSS and JavaScript files are always included and cannot be disabled. This ensures that all GCFoundation components work properly on every page..
        /// </summary>
        public static string GlobalResources_DefaultFilesNote {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultFilesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default JavaScript:.
        /// </summary>
        public static string GlobalResources_DefaultJavaScript_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultJavaScript_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates how to use the new global resources configuration feature in GCFoundation. You can configure CSS, JavaScript, meta tags, and link tags globally through the appsettings.json file..
        /// </summary>
        public static string GlobalResources_Description {
            get {
                return ResourceManager.GetString("GlobalResources_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Awesome:.
        /// </summary>
        public static string GlobalResources_FontAwesome_Label {
            get {
                return ResourceManager.GetString("GlobalResources_FontAwesome_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCDS Resources:.
        /// </summary>
        public static string GlobalResources_GCDSResources_Label {
            get {
                return ResourceManager.GetString("GlobalResources_GCDSResources_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global CSS Files.
        /// </summary>
        public static string GlobalResources_GlobalCssFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalCssFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global JavaScript Files.
        /// </summary>
        public static string GlobalResources_GlobalJavaScriptFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalJavaScriptFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Link Tags.
        /// </summary>
        public static string GlobalResources_GlobalLinkTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalLinkTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Meta Tags.
        /// </summary>
        public static string GlobalResources_GlobalMetaTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalMetaTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure global resources, update your &lt;code&gt;appsettings.json&lt;/code&gt; file:.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Description {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Configure.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Title {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Loading Order.
        /// </summary>
        public static string GlobalResources_JavaScriptLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_JavaScriptLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources are loaded in the following order:.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Description {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Loading Order.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global CSS files configured..
        /// </summary>
        public static string GlobalResources_NoCssFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoCssFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global JavaScript files configured..
        /// </summary>
        public static string GlobalResources_NoJavaScriptFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoJavaScriptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global link tags configured..
        /// </summary>
        public static string GlobalResources_NoLinkTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoLinkTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global meta tags configured..
        /// </summary>
        public static string GlobalResources_NoMetaTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Resources Configuration.
        /// </summary>
        public static string GlobalResources_Page_Title {
            get {
                return ResourceManager.GetString("GlobalResources_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following settings control which optional resources are included:.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Description {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Inclusion Settings.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Title {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use the &lt;code&gt;GlobalResourceHelper&lt;/code&gt; in your Razor views for more control:.
        /// </summary>
        public static string GlobalResources_UsingHelper_Description {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using GlobalResourceHelper in Views.
        /// </summary>
        public static string GlobalResources_UsingHelper_Title {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Index_Page_Title {
            get {
                return ResourceManager.GetString("Index_Page_Title", resourceCulture);
            }
        }
    }
}
