//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Installation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Installation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Installation", typeof(Installation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Enabled.
        /// </summary>
        public static string GlobalResources_AlwaysEnabled {
            get {
                return ResourceManager.GetString("GlobalResources_AlwaysEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Loading Order.
        /// </summary>
        public static string GlobalResources_CssLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CssLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following resources are currently configured to be loaded globally:.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Description {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CSS:.
        /// </summary>
        public static string GlobalResources_DefaultCss_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultCss_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Note:&lt;/strong&gt; Default foundation CSS and JavaScript files are always included and cannot be disabled. This ensures that all GCFoundation components work properly on every page..
        /// </summary>
        public static string GlobalResources_DefaultFilesNote {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultFilesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default JavaScript:.
        /// </summary>
        public static string GlobalResources_DefaultJavaScript_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultJavaScript_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates how to use the new global resources configuration feature in GCFoundation. You can configure CSS, JavaScript, meta tags, and link tags globally through the appsettings.json file..
        /// </summary>
        public static string GlobalResources_Description {
            get {
                return ResourceManager.GetString("GlobalResources_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Awesome:.
        /// </summary>
        public static string GlobalResources_FontAwesome_Label {
            get {
                return ResourceManager.GetString("GlobalResources_FontAwesome_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCDS Resources:.
        /// </summary>
        public static string GlobalResources_GCDSResources_Label {
            get {
                return ResourceManager.GetString("GlobalResources_GCDSResources_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global CSS Files.
        /// </summary>
        public static string GlobalResources_GlobalCssFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalCssFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global JavaScript Files.
        /// </summary>
        public static string GlobalResources_GlobalJavaScriptFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalJavaScriptFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Link Tags.
        /// </summary>
        public static string GlobalResources_GlobalLinkTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalLinkTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Meta Tags.
        /// </summary>
        public static string GlobalResources_GlobalMetaTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalMetaTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure global resources, update your &lt;code&gt;appsettings.json&lt;/code&gt; file:.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Description {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Configure.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Title {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Loading Order.
        /// </summary>
        public static string GlobalResources_JavaScriptLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_JavaScriptLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources are loaded in the following order:.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Description {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Loading Order.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global CSS files configured..
        /// </summary>
        public static string GlobalResources_NoCssFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoCssFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global JavaScript files configured..
        /// </summary>
        public static string GlobalResources_NoJavaScriptFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoJavaScriptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global link tags configured..
        /// </summary>
        public static string GlobalResources_NoLinkTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoLinkTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global meta tags configured..
        /// </summary>
        public static string GlobalResources_NoMetaTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Resources.
        /// </summary>
        public static string GlobalResources_Page_Title {
            get {
                return ResourceManager.GetString("GlobalResources_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following settings control which optional resources are included:.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Description {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Inclusion Settings.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Title {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use the &lt;code&gt;GlobalResourceHelper&lt;/code&gt; in your Razor views for more control:.
        /// </summary>
        public static string GlobalResources_UsingHelper_Description {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using GlobalResourceHelper in Views.
        /// </summary>
        public static string GlobalResources_UsingHelper_Title {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Index_Page_Title {
            get {
                return ResourceManager.GetString("Index_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Attributes&lt;/strong&gt;: Use either Name or Property (not both). Charset is standalone; HttpEquiv generally pairs with Content..
        /// </summary>
        public static string Metadata_Behavior_Item_Attributes {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;De-duplication&lt;/strong&gt;: A tag with the same Name or Property replaces the previous one. Global tags are only added if not already present..
        /// </summary>
        public static string Metadata_Behavior_Item_Dedup {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Dedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Encoding&lt;/strong&gt;: Attributes are HTML-encoded on render..
        /// </summary>
        public static string Metadata_Behavior_Item_Encoding {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;No view changes needed&lt;/strong&gt;: The layout picks up ViewData[&quot;MetaTags&quot;] automatically..
        /// </summary>
        public static string Metadata_Behavior_Item_NoViewChanges {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_NoViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Render order&lt;/strong&gt;: Controller tags render first, then non-duplicated global tags..
        /// </summary>
        public static string Metadata_Behavior_Item_Order {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set global, always-on meta tags in appsettings.json using the typed MetaTag structure:.
        /// </summary>
        public static string Metadata_Configuration_Paragraph {
            get {
                return ResourceManager.GetString("Metadata_Configuration_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates how metadata can be configured with GCFoundation. In addition to globally-defined metadata information, your application&apos;s metadata can be fully-customized on each page to allow for your application to be fully-optimized for search engines (i.e. SEO)..
        /// </summary>
        public static string Metadata_Description {
            get {
                return ResourceManager.GetString("Metadata_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior and rules.
        /// </summary>
        public static string Metadata_Heading_Behavior {
            get {
                return ResourceManager.GetString("Metadata_Heading_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Metadata_Heading_Configuration {
            get {
                return ResourceManager.GetString("Metadata_Heading_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Metadata_Heading_Examples {
            get {
                return ResourceManager.GetString("Metadata_Heading_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Metadata_Heading_HowItWorks {
            get {
                return ResourceManager.GetString("Metadata_Heading_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout rendering and merge.
        /// </summary>
        public static string Metadata_Heading_LayoutMerge {
            get {
                return ResourceManager.GetString("Metadata_Heading_LayoutMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes and gotchas.
        /// </summary>
        public static string Metadata_Heading_Notes {
            get {
                return ResourceManager.GetString("Metadata_Heading_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Metadata_Heading_Overview {
            get {
                return ResourceManager.GetString("Metadata_Heading_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage in controllers.
        /// </summary>
        public static string Metadata_Heading_Usage {
            get {
                return ResourceManager.GetString("Metadata_Heading_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers inheriting GCFoundationBaseController can add tags during action execution. The base class exposes them to the view post-action..
        /// </summary>
        public static string Metadata_HowItWorks_Paragraph {
            get {
                return ResourceManager.GetString("Metadata_HowItWorks_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foundation layout merges controller tags with global tags, avoiding duplicates by name or property. Controller tags are rendered first..
        /// </summary>
        public static string Metadata_LayoutMerge_Paragraph {
            get {
                return ResourceManager.GetString("Metadata_LayoutMerge_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior and rules.
        /// </summary>
        public static string Metadata_Nav_Behavior {
            get {
                return ResourceManager.GetString("Metadata_Nav_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Metadata_Nav_Configuration {
            get {
                return ResourceManager.GetString("Metadata_Nav_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Metadata_Nav_Examples {
            get {
                return ResourceManager.GetString("Metadata_Nav_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Metadata_Nav_HowItWorks {
            get {
                return ResourceManager.GetString("Metadata_Nav_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout rendering and merge.
        /// </summary>
        public static string Metadata_Nav_LayoutMerge {
            get {
                return ResourceManager.GetString("Metadata_Nav_LayoutMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes and gotchas.
        /// </summary>
        public static string Metadata_Nav_Notes {
            get {
                return ResourceManager.GetString("Metadata_Nav_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Metadata_Nav_Overview {
            get {
                return ResourceManager.GetString("Metadata_Nav_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage in controllers.
        /// </summary>
        public static string Metadata_Nav_Usage {
            get {
                return ResourceManager.GetString("Metadata_Nav_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Base class requirement&lt;/strong&gt;: Controllers must inherit GCFoundationBaseController to use AddMetaTag..
        /// </summary>
        public static string Metadata_Notes_Item_BaseClass {
            get {
                return ResourceManager.GetString("Metadata_Notes_Item_BaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Optional section&lt;/strong&gt;: @section Metas { ... } remains available for manual HTML if needed, but is not required..
        /// </summary>
        public static string Metadata_Notes_Item_OptionalSection {
            get {
                return ResourceManager.GetString("Metadata_Notes_Item_OptionalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Base controller support&lt;/strong&gt;: GCFoundationBaseController collects per-page meta tags and exposes them to views via ViewData[&quot;MetaTags&quot;] after each action..
        /// </summary>
        public static string Metadata_Overview_Item_BaseController {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_BaseController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Configuration&lt;/strong&gt;: GlobalMetaTags in GCFoundationComponentsSettings is a collection of typed MetaTag objects (appsettings.json)..
        /// </summary>
        public static string Metadata_Overview_Item_Configuration {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Layout rendering and merge&lt;/strong&gt;: _FoundationLayout.cshtml merges controller-provided tags with configured global tags, avoiding duplicates by name or property. Controller tags take precedence..
        /// </summary>
        public static string Metadata_Overview_Item_LayoutMerge {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_LayoutMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Strongly-typed model&lt;/strong&gt;: MetaTag supports name/content, property/content (Open Graph, Twitter), http-equiv/content, and charset..
        /// </summary>
        public static string Metadata_Overview_Item_TypedModel {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_TypedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata_Page_Title {
            get {
                return ResourceManager.GetString("Metadata_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page.
        /// </summary>
        public static string Metadata_SideNav_OnThisPage {
            get {
                return ResourceManager.GetString("Metadata_SideNav_OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit from GCFoundationBaseController and call AddMetaTag in your action..
        /// </summary>
        public static string Metadata_Usage_Paragraph {
            get {
                return ResourceManager.GetString("Metadata_Usage_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As part of the GCFoundation, you also get a set of standard translations that you can use in your GCFoundation applications..
        /// </summary>
        public static string Translations_Description {
            get {
                return ResourceManager.GetString("Translations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Translations.
        /// </summary>
        public static string Translations_Page_Title {
            get {
                return ResourceManager.GetString("Translations_Page_Title", resourceCulture);
            }
        }
    }
}
