# UAT AppSettings Variables
variables:
- name: Infrastructure.Environment
  value: 'UAT'

- name: FoundationComponentsSettings.VirtualDirectoryName
  value: 'gcfoundation'

- name: ASPNETCORE_PATHBASE
  value: '/gcfoundation'