# UAT Deployment variables
variables:
- name: azureSubscription
  value: 'Infosite_Apps_WebApp'

- name: deploymentEnvironment
  value: 'uat'

- name: resourceGroupName
  value: 'rg_tbs_webapps'

- name: slotName
  value: 'wapp-apps-tbs-uat01'

- name: useSlot
  value: 'true'

- name: virtualDirectoryName
  value: 'gcfoundation'

- name: webAppName
  value: 'appsvc-apps-tbs-win001'