# PROD AppSettings Variables
variables:
- name: Infrastructure.Environment
  value: 'PROD'

- name: FoundationComponentsSettings.VirtualDirectoryName
  value: 'gcfoundation'

- name: ASPNETCORE_PATHBASE
  value: '/gcfoundation'