# PROD Deployment variables
variables:
- name: azureSubscription
  value: 'Infosite_Apps_WebApp'

- name: deploymentEnvironment
  value: 'prod'

- name: resourceGroupName
  value: 'rg_tbs_webapps'

- name: slotName
  value: 'production'

- name: virtualDirectoryName
  value: 'gcfoundation'

- name: webAppName
  value: 'appsvc-apps-tbs-win001'