<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>All</AnalysisMode>

    <PackageId>GCFoundation.Security</PackageId>
    <Version>1.0.0</Version>
    <Authors>Philippe G. Vadnais</Authors>
    <Company>TBS-SCT</Company>
    <Description>Security middleware and helpers for GCFoundation applications.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/tbs-imtd/GCFoundation</RepositoryUrl>
    <PackageProjectUrl>https://github.com/tbs-imtd/GCFoundation</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <PackageTags>GCFoundation;GCDS;GC Design System;Government of Canada;Security;CSP;Headers;ASP.NET;NET</PackageTags>
    <ErrorLog>Foundation.Components.Security.sarif,version=2.1</ErrorLog>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCFoundation.Common\GCFoundation.Common.csproj" />
  </ItemGroup>

  <!-- README for NuGet.org -->
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
